/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rent_to_go;

import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class AdminCompleteBookingList extends javax.swing.JFrame {
    Admin admin;
    /**
     * Creates new form AdminCompleteBookingList
     */
    public AdminCompleteBookingList() throws IOException {
        initComponents();
        this.getContentPane().setBackground(new Color(228,231,242));
        ImageIcon image = new ImageIcon("./src/main/java/com/mycompany/rent_to_go/Pictures/rsz_renttogologo.jpg");
        lblLogo.setIcon(image);
        lblLogo.setText("");
        btnRentalStatus.setVisible(true);
        fillBookingListTable();
        btnRentalStatus.setVisible(false);
     
    }
    
    public AdminCompleteBookingList(Admin admin) throws IOException {
        this.admin = admin;
        initComponents();
        this.getContentPane().setBackground(new Color(228,231,242));
        ImageIcon image = new ImageIcon("./src/main/java/com/mycompany/rent_to_go/Pictures/rsz_renttogologo.jpg");
        lblLogo.setIcon(image);
        lblLogo.setText("");
        btnRentalStatus.setVisible(true);
        fillBookingListTable();
        btnRentalStatus.setVisible(false);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableBooking2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnRentalStatus = new javax.swing.JButton();
        cboRentalStatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLogo.setText("jLabel2");

        btnBack.setBackground(new java.awt.Color(240, 240, 192));
        btnBack.setForeground(new java.awt.Color(0, 0, 102));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tableBooking2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking ID", "Customer ID", "Car ID", "Rental Status", "Total Price (RM)", "Pickup Date", "DropOff Date", "Pickup Location", "DropOff Location", "Rental Duration (h)"
            }
        ));
        tableBooking2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBooking2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableBooking2);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Bookings List");

        btnRentalStatus.setBackground(new java.awt.Color(240, 240, 192));
        btnRentalStatus.setForeground(new java.awt.Color(0, 0, 102));
        btnRentalStatus.setText("Edit Rental Status");
        btnRentalStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentalStatusActionPerformed(evt);
            }
        });

        cboRentalStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Approved", "Picked Up", "Dropped Off" }));
        cboRentalStatus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboRentalStatusItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 615, Short.MAX_VALUE)
                .addComponent(btnBack))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRentalStatus)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(237, 237, 237)
                            .addComponent(cboRentalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnBack)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(cboRentalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnRentalStatus)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void fillBookingListTable() throws IOException{
        DefaultTableModel model = (DefaultTableModel) tableBooking2.getModel();
        model.setRowCount(0);
        for(CarBooking booking: CarBooking.getOngoingBookings()){
                model.addRow(new Object[]{booking.getBookingId(), booking.getCustomer().getCustomerId(), booking.getCar().getCarId(), booking.getRentalStatus(), booking.getPayment().getTotalPayment(), booking.getPickupDate(), booking.getDropOffDate() , booking.getPickupLocation(), booking.getDropOffLocation(), booking.getTotalHours()});

        }
    }
    
    public void fillFilteredBookingListTable(ArrayList<CarBooking> bookingList){
        DefaultTableModel model = (DefaultTableModel) tableBooking2.getModel();
        model.setRowCount(0);
        for(CarBooking booking: bookingList){
                model.addRow(new Object[]{booking.getBookingId(), booking.getCustomer().getCustomerId(), booking.getCar().getCarId(), booking.getRentalStatus(), booking.getPayment().getTotalPayment(), booking.getPickupDate(), booking.getDropOffDate() , booking.getPickupLocation(), booking.getDropOffLocation(), booking.getTotalHours()});

        }
    }
    
    private void tableBooking2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBooking2MouseClicked
        // TODO add your handling code here:
        btnRentalStatus.setVisible(true);

    }//GEN-LAST:event_tableBooking2MouseClicked

    private void btnRentalStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentalStatusActionPerformed
        try {
            // TODO add your handling code here:
            CarBooking carBooking = CarBooking.getCarBooking((String)tableBooking2.getValueAt(tableBooking2.getSelectedRow(), 0));
            AdminRentalStatusUpdate rentalStatus = new AdminRentalStatusUpdate(carBooking);
            rentalStatus.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(AdminCompleteBookingList.class.getName()).log(Level.SEVERE, null, ex);
        }
          
        
        
    }//GEN-LAST:event_btnRentalStatusActionPerformed

    private void cboRentalStatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboRentalStatusItemStateChanged
        // TODO add your handling code here:
         if(((String)cboRentalStatus.getSelectedItem()).equals("Approved")){
            try {
                fillFilteredBookingListTable(CarBooking.getApprovedBookings());
            } catch (IOException ex) {
                Logger.getLogger(AdminCompleteBookingList.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(((String)cboRentalStatus.getSelectedItem()).equals("Picked Up")){
            try {
                fillFilteredBookingListTable(CarBooking.getPickUpBookings());
            } catch (IOException ex) {
                Logger.getLogger(AdminCompleteBookingList.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(((String)cboRentalStatus.getSelectedItem()).equals("Dropped Off")){
            try {
                fillFilteredBookingListTable(CarBooking.getDropOffBookings());
            } catch (IOException ex) {
                Logger.getLogger(AdminCompleteBookingList.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            try {
                fillBookingListTable();
            } catch (IOException ex) {
                Logger.getLogger(AdminCompleteBookingList.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cboRentalStatusItemStateChanged

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        AdminBookingList bookingList;
        try {
            bookingList = new AdminBookingList(admin);
            this.setVisible(false);
            bookingList.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(AdminCompleteBookingList.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminCompleteBookingList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminCompleteBookingList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminCompleteBookingList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminCompleteBookingList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AdminCompleteBookingList().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(AdminCompleteBookingList.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRentalStatus;
    private javax.swing.JComboBox<String> cboRentalStatus;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JTable tableBooking2;
    // End of variables declaration//GEN-END:variables
}
