/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rent_to_go;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class AdminRentalStatusUpdate extends javax.swing.JFrame {
    Notification notification;
    CarBooking booking;
    Admin admin;

    /**
     * Creates new form AdminRentalStatusUpdate
     */
    public AdminRentalStatusUpdate() {
        initComponents();
         this.getContentPane().setBackground(new Color(240,240,192));
        ImageIcon image = new ImageIcon("./src/main/java/com/mycompany/rent_to_go/Pictures/rsz_renttogologo.jpg");
       
        
    }
    public AdminRentalStatusUpdate(CarBooking booking){
    
        this.booking = booking;
          initComponents();
         this.getContentPane().setBackground(new Color(240,240,192));
        ImageIcon image = new ImageIcon("./src/main/java/com/mycompany/rent_to_go/Pictures/rsz_renttogologo.jpg");
       txtBookingId.setText(booking.getBookingId());
       
       if(booking.getRentalStatus().equals(RentalStatus.pickedUp)){
           cboBookingStatus.removeItemAt(0);
       }
       if(booking.getRentalStatus().equals(RentalStatus.dropedOff)){
           cboBookingStatus.removeItemAt(0);
           cboBookingStatus.removeItemAt(0);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        txtBookingId = new javax.swing.JTextField();
        lblName1 = new javax.swing.JLabel();
        cboBookingStatus = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblName.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblName.setText("Booking ID:");

        lblName1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblName1.setText("Booking Status:");

        cboBookingStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Approved", "Picked Up", "Dropped Off" }));

        btnUpdate.setBackground(new java.awt.Color(228, 231, 242));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblName)
                            .addComponent(lblName1))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBookingId)
                            .addComponent(cboBookingStatus, 0, 125, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btnUpdate)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBookingId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName1)
                    .addComponent(cboBookingStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnUpdate)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        
        if(cboBookingStatus.getSelectedItem().equals("Approved")){
             booking.setRentalStatus(RentalStatus.approved);
             
         }else if(cboBookingStatus.getSelectedItem().equals("Picked Up")){
             booking.setRentalStatus(RentalStatus.pickedUp);
             
            try {
                notification = new Notification("Your booking status has been changed from approved to picked-up", booking.getBookingId());
                booking.addNotificationList(notification);
            } catch (IOException ex) {
                Logger.getLogger(AdminRentalStatusUpdate.class.getName()).log(Level.SEVERE, null, ex);
            }
             
         }else{
            
             booking.setRentalStatus(RentalStatus.dropedOff);
            try {
                notification = new Notification("Your booking status has been changed from picked-up to dropped off", booking.getBookingId());
                booking.addNotificationList(notification);
            } catch (IOException ex) {
                Logger.getLogger(AdminRentalStatusUpdate.class.getName()).log(Level.SEVERE, null, ex);
            }
             
         }
        try {
            CarBooking.modifyBookingStatus(booking);
            JOptionPane.showMessageDialog(null, "The booking status has been successfully updated.", "title", JOptionPane.PLAIN_MESSAGE);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(AdminRentalStatusUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminRentalStatusUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminRentalStatusUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminRentalStatusUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRentalStatusUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminRentalStatusUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboBookingStatus;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JTextField txtBookingId;
    // End of variables declaration//GEN-END:variables
}
