/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rent_to_go;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class AdminCarDetails extends javax.swing.JFrame {
    Car car;
    Admin admin;

    /**
     * Creates new form AdminCarDetails
     */
    public AdminCarDetails() {
        initComponents();
        this.getContentPane().setBackground(new Color(228,231,242));
        ImageIcon image = new ImageIcon("./src/main/java/com/mycompany/rent_to_go/Pictures/rsz_renttogologo.jpg");
        lblLogo.setIcon(image);
        lblLogo.setText("");
  
    }
    
    public AdminCarDetails(Car car, Admin admin) throws IOException{
        initComponents();
        this.admin = admin;
        this.car = car;
        this.getContentPane().setBackground(new Color(228,231,242));
        ImageIcon image = new ImageIcon("./src/main/java/com/mycompany/rent_to_go/Pictures/rsz_renttogologo.jpg");
        lblLogo.setIcon(image);
        lblLogo.setText("");
        lblYearError.setVisible(false);
        lblPriceError.setVisible(false);
        lblPasError.setVisible(false);
       
        txtMake.setText(car.getMake());
        txtModel.setText(car.getModel());
        txtPlateNum.setText(car.getPlateNumber());
        txtPasCap.setText(String.valueOf(car.getPassengerCapacity()));
        txtLugCap.setText(String.valueOf(car.getLuggageCapacity()));
        txtManYear.setText(String.valueOf(car.getManufacturingYear()));
        txtPricePerHour.setText(String.valueOf(car.getPricePerHour()));
        setNonEditable();
        fillBookings(car);
        
    }
   public void fillBookings(Car car) throws IOException{
        DefaultTableModel model = (DefaultTableModel) tableBooking.getModel();

        for(CarBooking booking: CarBooking.getSpecificCarBooking(car)){
                model.addRow(new Object[]{booking.getBookingId(), booking.getRentalStatus(), booking.getPayment().getTotalPayment(), booking.getPickupDate(), booking.getDropOffDate() , booking.getPickupLocation(), booking.getDropOffLocation(), booking.getTotalHours()});

        }
    }
   
   public void setEditable(){
       cboTransmission.setEditable(true);
       txtMake.setEditable(true);
       txtModel.setEditable(true);
       txtPlateNum.setEditable(true);
       txtPasCap.setEditable(true);
       txtLugCap.setEditable(true);
       txtManYear.setEditable(true);
       txtPricePerHour.setEditable(true);
       
       
   }
   
   public void setNonEditable(){
       cboTransmission.setEditable(false);
       txtMake.setEditable(false);
       txtModel.setEditable(false);
       txtPlateNum.setEditable(false);
       txtPasCap.setEditable(false);
       txtLugCap.setEditable(false);
       txtManYear.setEditable(false);
       txtPricePerHour.setEditable(false);
   }
   
   
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnManage = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBooking = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblName1 = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        lblName2 = new javax.swing.JLabel();
        txtMake = new javax.swing.JTextField();
        txtPlateNum = new javax.swing.JTextField();
        lblName3 = new javax.swing.JLabel();
        lblName4 = new javax.swing.JLabel();
        txtPasCap = new javax.swing.JTextField();
        lblName6 = new javax.swing.JLabel();
        txtManYear = new javax.swing.JTextField();
        lblName7 = new javax.swing.JLabel();
        txtPricePerHour = new javax.swing.JTextField();
        lblPriceError = new javax.swing.JLabel();
        lblYearError = new javax.swing.JLabel();
        lblPasError = new javax.swing.JLabel();
        lblName8 = new javax.swing.JLabel();
        txtLugCap = new javax.swing.JTextField();
        lblName9 = new javax.swing.JLabel();
        cboTransmission = new javax.swing.JComboBox<>();
        cboRentalCenter = new javax.swing.JComboBox<>();
        lblName5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLogo.setText("jLabel2");

        btnBack.setBackground(new java.awt.Color(240, 240, 192));
        btnBack.setForeground(new java.awt.Color(0, 0, 102));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Car Details");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Car Bookings");

        btnManage.setBackground(new java.awt.Color(240, 240, 192));
        btnManage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnManage.setForeground(new java.awt.Color(0, 0, 102));
        btnManage.setText("Edit Details");
        btnManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageActionPerformed(evt);
            }
        });

        tableBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking ID", "Rental Status", "Total Price (RM)", "Pickup Date", "DropOff Date", "Pickup Location", "DropOff Location", "Rental Duration (h)"
            }
        ));
        jScrollPane1.setViewportView(tableBooking);

        jPanel1.setBackground(new java.awt.Color(240, 240, 192));

        lblName1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblName1.setText("Make:");

        lblName2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblName2.setText("Model:");

        lblName3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblName3.setText("Plate Number:");

        lblName4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblName4.setText("Passenger Capacity:");

        txtPasCap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasCapKeyReleased(evt);
            }
        });

        lblName6.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblName6.setText("Transmission");

        txtManYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtManYearKeyReleased(evt);
            }
        });

        lblName7.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblName7.setText("Price Per Hour(RM):");

        txtPricePerHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPricePerHourActionPerformed(evt);
            }
        });
        txtPricePerHour.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPricePerHourKeyReleased(evt);
            }
        });

        lblPriceError.setBackground(new java.awt.Color(255, 102, 102));
        lblPriceError.setText("Enter a valid price");
        lblPriceError.setOpaque(true);
        lblPriceError.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblPriceErrorKeyReleased(evt);
            }
        });

        lblYearError.setBackground(new java.awt.Color(255, 102, 102));
        lblYearError.setText("Enter a valid year");
        lblYearError.setOpaque(true);
        lblYearError.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblYearErrorKeyReleased(evt);
            }
        });

        lblPasError.setBackground(new java.awt.Color(255, 102, 102));
        lblPasError.setText("Enter a valid value");
        lblPasError.setOpaque(true);
        lblPasError.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblPasErrorKeyReleased(evt);
            }
        });

        lblName8.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblName8.setText("Luggage Capacity(kg)");

        lblName9.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblName9.setText("Manufacturing Year:");

        cboTransmission.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auto", "Manual" }));

        cboRentalCenter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "George Town Rental Centre", "Kuala Lumpur Rental Centre", "Johor Bahru Rental Centre" }));

        lblName5.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblName5.setText("Rental Center");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName1)
                            .addComponent(lblName3)
                            .addComponent(lblName2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(txtPlateNum, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtModel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblName4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPasCap, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblPasError, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPriceError, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblName7)
                                .addGap(22, 22, 22)
                                .addComponent(txtPricePerHour, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName8)
                                    .addComponent(lblName6))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboTransmission, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLugCap, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblYearError, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblName9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtManYear, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(4, 4, 4)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblName5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(cboRentalCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName2)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName6)
                            .addComponent(cboTransmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName1)
                            .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName8)
                            .addComponent(txtLugCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPlateNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblName3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtManYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName9))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(lblYearError))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName7)
                            .addComponent(txtPricePerHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPriceError))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPasCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPasError)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName5)
                    .addComponent(cboRentalCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(236, 236, 236)
                                        .addComponent(btnManage)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnBack)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManage)
                        .addGap(214, 214, 214))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageActionPerformed
        // TODO add your handling code here:
        if(btnManage.getText().equals("Edit Details")){
            setEditable();
            btnManage.setText("Save Details");
        }else{
            try {
                saveDetails();
            } catch (IOException ex) {
                Logger.getLogger(AdminCarDetails.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnManageActionPerformed

    private void txtPasCapKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasCapKeyReleased
        // TODO add your handling code here:
        if(DetailsValidator.numberValidator(txtPasCap.getText())){
            lblPasError.setVisible(false);
        }else{
            lblPasError.setVisible(true);
        }
    }//GEN-LAST:event_txtPasCapKeyReleased

    private void txtManYearKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtManYearKeyReleased
        // TODO add your handling code here:
        if(DetailsValidator.pastYearValidator(txtManYear.getText())){
            lblYearError.setVisible(false);
        }else{
            lblYearError.setVisible(true);
        }

    }//GEN-LAST:event_txtManYearKeyReleased

    private void txtPricePerHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPricePerHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPricePerHourActionPerformed

    private void txtPricePerHourKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPricePerHourKeyReleased
        // TODO add your handling code here:
        if(DetailsValidator.priceValidator(txtPricePerHour.getText())){
            lblPriceError.setVisible(false);
        }else{
            lblPriceError.setVisible(true);
        }
    }//GEN-LAST:event_txtPricePerHourKeyReleased

    private void lblPriceErrorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblPriceErrorKeyReleased
        // TODO add your handling code here:
        lblPriceError.setVisible(true);
    }//GEN-LAST:event_lblPriceErrorKeyReleased

    private void lblYearErrorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblYearErrorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblYearErrorKeyReleased

    private void lblPasErrorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblPasErrorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPasErrorKeyReleased

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        AdminCarList carListPage;
        try {
            carListPage = new AdminCarList(admin);
            carListPage.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(AdminCarDetails.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnBackActionPerformed

    public boolean checkEmptyFields(){
        if(txtModel.getText().length()==0 || txtMake.getText().length()==0 || txtPlateNum.getText().length()==0 || txtPasCap.getText().length()==0 || txtLugCap.getText().length()==0 || txtManYear.getText().length()==0 || txtPricePerHour.getText().length()==0){
            return true;
        }
        return false;
    }

    public void saveDetails() throws IOException{
        if(checkEmptyFields()){
                JOptionPane.showMessageDialog(null, "Please make sure that you have entered all the required details", "title", JOptionPane.PLAIN_MESSAGE);
            
        }

        else if(lblPriceError.isVisible() || lblYearError.isVisible() || lblPasError.isVisible()){
                JOptionPane.showMessageDialog(null, "Invalid Details Entered", "title", JOptionPane.PLAIN_MESSAGE);

        }
        else if(!DetailsValidator.weightValidator(txtLugCap.getText())){
                JOptionPane.showMessageDialog(null, "Please enter a valid value for luggage capacity", "title", JOptionPane.PLAIN_MESSAGE);
        }
        else{
            car.setMake(txtMake.getText());
            car.setModel(txtModel.getText());
            car.setPlateNumber(txtPlateNum.getText());
            car.setPassengerCapacity(Integer.valueOf(txtPasCap.getText()));
            car.setLuggageCapacity(Double.valueOf(txtLugCap.getText()));
            car.setTransmission((String)cboTransmission.getSelectedItem());
            car.setPricePerHour(Double.valueOf(txtPricePerHour.getText()));
            car.setManufacturingYear(Integer.valueOf(txtManYear.getText()));
            car.setRentalCenter((String) cboRentalCenter.getSelectedItem());
            
            Car.modifyCar(car);
            
            JOptionPane.showMessageDialog(null, "The car details has been successfully modified", "title", JOptionPane.PLAIN_MESSAGE);

            setNonEditable();
            btnManage.setText("Edit Details");

            
        }
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminCarDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminCarDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminCarDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminCarDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminCarDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnManage;
    private javax.swing.JComboBox<String> cboRentalCenter;
    private javax.swing.JComboBox<String> cboTransmission;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblName4;
    private javax.swing.JLabel lblName5;
    private javax.swing.JLabel lblName6;
    private javax.swing.JLabel lblName7;
    private javax.swing.JLabel lblName8;
    private javax.swing.JLabel lblName9;
    private javax.swing.JLabel lblPasError;
    private javax.swing.JLabel lblPriceError;
    private javax.swing.JLabel lblYearError;
    private javax.swing.JTable tableBooking;
    private javax.swing.JTextField txtLugCap;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtManYear;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtPasCap;
    private javax.swing.JTextField txtPlateNum;
    private javax.swing.JTextField txtPricePerHour;
    // End of variables declaration//GEN-END:variables
}
