/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.rent_to_go;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class BookingResult extends javax.swing.JPanel {
    CarBooking booking;

    /**
     * Creates new form BookingResult
     */
    public BookingResult() {
        initComponents();

    }
    
    public BookingResult(CarBooking booking){
        this.booking = booking;
        initComponents();
        ImageIcon image = new ImageIcon("./src/main/java/com/mycompany/rent_to_go/Pictures/rsz_car.png");
        ImageIcon image2 = new ImageIcon("./src/main/java/com/mycompany/rent_to_go/Pictures/rejected_icon.png");
        ImageIcon image3 = new ImageIcon("./src/main/java/com/mycompany/rent_to_go/Pictures/complete_icon.png");
        lblCar.setIcon(image);
        lblCar.setText("");
        lblPickupDatetime.setText(booking.getPickupDate() + " | " +  this.booking.getFormattedPickupTime());
        lblDropDatetime.setText(booking.getDropOffDate() + " | " +  this.booking.getFormattedDropOffTime());
        lblPickupLocation.setText(booking.getPickupLocation());
        lblDropOffLocation.setText(booking.getDropOffLocation());
        lblBookingId.setText("Booking ID: " + booking.getBookingId());
        if(booking.getRentalStatus().equals(RentalStatus.rejected)){
            
            this.setBackground(new Color(255,102,102));
            lblCar.setIcon(image2);
        }
        if(booking.getRentalStatus().equals(RentalStatus.dropedOff)){
            this.setBackground(new Color(0,209,0));
            lblCar.setIcon(image3);
        }
        if(booking.getRentalStatus().equals(RentalStatus.approved) || booking.getRentalStatus().equals(RentalStatus.checkedOut) || booking.getRentalStatus().equals(RentalStatus.pickedUp) || booking.getRentalStatus().equals(RentalStatus.rejected)){
            btnBooking.setText("View Rental Status");
        }else{
            btnBooking.setText("Leave a Review");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        lblDropDatetime = new javax.swing.JLabel();
        lblDropOffLocation = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblPickupDatetime = new javax.swing.JLabel();
        lblPickupLocation = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblCar = new javax.swing.JLabel();
        btnBooking = new javax.swing.JButton();
        btnPaymentReceipt = new javax.swing.JButton();
        lblBookingId = new javax.swing.JLabel();

        setBackground(new java.awt.Color(67, 136, 204));

        jPanel6.setBackground(new java.awt.Color(67, 136, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));

        lblDropDatetime.setForeground(new java.awt.Color(255, 255, 255));
        lblDropDatetime.setText("12/10/2022 11:30");

        lblDropOffLocation.setForeground(new java.awt.Color(255, 255, 255));
        lblDropOffLocation.setText("George Town Rental Centre");

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Drop-Off");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDropOffLocation)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(lblDropDatetime)
                                .addGap(23, 23, 23)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(lblDropDatetime)
                .addGap(28, 28, 28)
                .addComponent(lblDropOffLocation)
                .addGap(19, 19, 19))
        );

        jPanel4.setBackground(new java.awt.Color(67, 136, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));

        lblPickupDatetime.setForeground(new java.awt.Color(255, 255, 255));
        lblPickupDatetime.setText("12/12/2022 10:30");

        lblPickupLocation.setForeground(new java.awt.Color(255, 255, 255));
        lblPickupLocation.setText("George Town Rental Centre");

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Pick-Up");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblPickupLocation))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblPickupDatetime))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel14)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(lblPickupDatetime)
                .addGap(29, 29, 29)
                .addComponent(lblPickupLocation)
                .addGap(20, 20, 20))
        );

        jSeparator1.setBackground(new java.awt.Color(255, 255, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 51));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));

        lblCar.setText("jLabel1");

        btnBooking.setBackground(new java.awt.Color(255, 255, 0));
        btnBooking.setText("Leave A Review");
        btnBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingActionPerformed(evt);
            }
        });

        btnPaymentReceipt.setBackground(new java.awt.Color(255, 255, 0));
        btnPaymentReceipt.setText("View Payment Receipt");
        btnPaymentReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentReceiptActionPerformed(evt);
            }
        });

        lblBookingId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBookingId.setForeground(new java.awt.Color(255, 255, 255));
        lblBookingId.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblCar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblBookingId)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPaymentReceipt)
                        .addGap(28, 28, 28)
                        .addComponent(btnBooking))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPaymentReceipt)
                            .addComponent(btnBooking)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBookingId)
                        .addGap(28, 28, 28)
                        .addComponent(lblCar)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingActionPerformed
        // TODO add your handling code here:
        if(btnBooking.getText().equals("Leave a Review")){
            CustomerReview reviewPage = new CustomerReview(booking);
            reviewPage.setVisible(true);
            javax.swing.SwingUtilities.getWindowAncestor(BookingResult.this).dispose();
        }else{
            CustomerRentalStatus rentalStatus;
            try {
                rentalStatus = new CustomerRentalStatus(booking);
                rentalStatus.setVisible(true);
                javax.swing.SwingUtilities.getWindowAncestor(BookingResult.this).dispose();
            } catch (IOException ex) {
                Logger.getLogger(BookingResult.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
    }//GEN-LAST:event_btnBookingActionPerformed

    private void btnPaymentReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentReceiptActionPerformed
        // TODO add your handling code here:
        CustomerPaymentReceipt payReceipt = new CustomerPaymentReceipt(booking);
        payReceipt.setVisible(true);
        javax.swing.SwingUtilities.getWindowAncestor(BookingResult.this).dispose();
    }//GEN-LAST:event_btnPaymentReceiptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBooking;
    private javax.swing.JButton btnPaymentReceipt;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBookingId;
    private javax.swing.JLabel lblCar;
    private javax.swing.JLabel lblDropDatetime;
    private javax.swing.JLabel lblDropOffLocation;
    private javax.swing.JLabel lblPickupDatetime;
    private javax.swing.JLabel lblPickupLocation;
    // End of variables declaration//GEN-END:variables
}
