/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rent_to_go;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author User
 */
public class SummaryStatistics extends javax.swing.JFrame {
    Admin admin;
    MonthlyCarReport carReport;
    int currentSelection=1;
    

    /**
     * Creates new form SummaryStatistics
     */
    public SummaryStatistics() throws IOException {
        initComponents();
   
        

    }
    
    
    public SummaryStatistics(Admin admin) throws IOException {
        this.admin = admin;
        initComponents();
        
        resultPanel.setLayout(new BorderLayout());
        this.getContentPane().setBackground(new Color(228,231,242));
        ImageIcon image = new ImageIcon("./src/main/java/com/mycompany/rent_to_go/Pictures/rsz_renttogologo.jpg");
        ImageIcon image2 = new ImageIcon("./src/main/java/com/mycompany/rent_to_go/Pictures/rsz_1rsz_1rsz_profile.png");
        lblLogo.setIcon(image);
        lblLogo.setText("");
        carReport = new MonthlyCarReport((String) cboMonth.getSelectedItem());
        generateRentalRateStat();  
        

    }

    
    public void generateRentalEarningStat() throws IOException{
        DefaultCategoryDataset dod = new DefaultCategoryDataset();
        for(ArrayList<String> carData: carReport.getEarningPerCar()){
            dod.setValue(Double.valueOf(carData.get(1)), "Total Earnings", carData.get(0));
        }

        JFreeChart jchart = ChartFactory.createBarChart("Total Earnings Per Car", "Car Id", 
                "Total Earnings", dod, PlotOrientation.VERTICAL, 
                false, true, false);
        CategoryPlot plot = jchart.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.black);
        
        ChartPanel chartPanel = new ChartPanel(jchart);
  
        resultPanel.removeAll();
       
        resultPanel.add(chartPanel, BorderLayout.CENTER);
        resultPanel.revalidate();
        this.repaint();
    }
    

    
    
    public void generateRentalRateStat() throws IOException{
        DefaultCategoryDataset dod = new DefaultCategoryDataset();
        for(ArrayList<String> carData: carReport.getNumPerCar()){
            dod.setValue(Integer.valueOf(carData.get(1)), "Number of Rentals", carData.get(0));
        }

        JFreeChart jchart = ChartFactory.createBarChart("Total Rentals Per Car", "Car Id", "Total Rentals", dod, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot plot = jchart.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.black);
        
        ChartPanel chartPanel = new ChartPanel(jchart);
  
        resultPanel.removeAll();
       
        resultPanel.add(chartPanel, BorderLayout.CENTER);
        resultPanel.revalidate();
        this.repaint();
    }
    
    
    public void generateRentalDurationStat() throws IOException{
        DefaultCategoryDataset dod = new DefaultCategoryDataset();
        for(ArrayList<String> carData: carReport.getDurationPerCar()){
            dod.setValue(Double.valueOf(carData.get(1)), "Total Rental Duration", carData.get(0));
        }

        JFreeChart jchart = ChartFactory.createBarChart("Total Rental Duration(h) Per Car", "Car Id", "Total Rental Duration", dod, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot plot = jchart.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.black);
        
        ChartPanel chartPanel = new ChartPanel(jchart);
  
        resultPanel.removeAll();
       
        resultPanel.add(chartPanel, BorderLayout.CENTER);
        resultPanel.revalidate();
        this.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        resultPanel = new javax.swing.JPanel();
        btnRentalCount = new javax.swing.JButton();
        btnEarning = new javax.swing.JButton();
        btnDuration = new javax.swing.JButton();
        btnPrintChart = new javax.swing.JButton();
        cboMonth = new javax.swing.JComboBox<>();
        btnPrint1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLogo.setText("jLabel2");

        btnBack.setBackground(new java.awt.Color(240, 240, 192));
        btnBack.setForeground(new java.awt.Color(0, 0, 102));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        resultPanel.setBackground(new java.awt.Color(204, 0, 204));
        resultPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(resultPanel);
        resultPanel.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );

        btnRentalCount.setBackground(new java.awt.Color(67, 136, 204));
        btnRentalCount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRentalCount.setForeground(new java.awt.Color(255, 255, 0));
        btnRentalCount.setText("Rental Rate Per Car");
        btnRentalCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentalCountActionPerformed(evt);
            }
        });

        btnEarning.setBackground(new java.awt.Color(67, 136, 204));
        btnEarning.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEarning.setForeground(new java.awt.Color(255, 255, 0));
        btnEarning.setText("Total Earnings Per Car");
        btnEarning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEarningActionPerformed(evt);
            }
        });

        btnDuration.setBackground(new java.awt.Color(67, 136, 204));
        btnDuration.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDuration.setForeground(new java.awt.Color(255, 255, 0));
        btnDuration.setText("Total Rental Duration Per Car");
        btnDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDurationActionPerformed(evt);
            }
        });

        btnPrintChart.setBackground(new java.awt.Color(240, 240, 192));
        btnPrintChart.setForeground(new java.awt.Color(0, 0, 102));
        btnPrintChart.setText("Print Chart");
        btnPrintChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintChartActionPerformed(evt);
            }
        });

        cboMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        btnPrint1.setBackground(new java.awt.Color(240, 240, 192));
        btnPrint1.setForeground(new java.awt.Color(0, 0, 102));
        btnPrint1.setText("Generate");
        btnPrint1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrint1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRentalCount)
                        .addGap(43, 43, 43)
                        .addComponent(btnEarning)
                        .addGap(26, 26, 26)
                        .addComponent(btnDuration)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrint1)
                        .addGap(188, 188, 188)
                        .addComponent(btnBack)))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(resultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrintChart)
                .addGap(372, 372, 372))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBack)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPrint1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRentalCount)
                            .addComponent(btnEarning)
                            .addComponent(btnDuration))
                        .addGap(9, 9, 9)))
                .addComponent(resultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrintChart)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRentalCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentalCountActionPerformed
        try {
            // TODO add your handling code here:
            currentSelection = 1;
            btnRentalCount.setBackground(Color.blue);
            btnEarning.setBackground(new Color(67,136,204));
            btnDuration.setBackground(new Color(7,136,204));
            generateRentalRateStat();
        } catch (IOException ex) {
            Logger.getLogger(SummaryStatistics.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRentalCountActionPerformed

    private void btnEarningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEarningActionPerformed
        try {
            // TODO add your handling code here:
            currentSelection = 2;
            btnRentalCount.setBackground(new Color(7,136,204));
            btnEarning.setBackground(Color.blue);
            btnDuration.setBackground(new Color(7,136,204));
            generateRentalEarningStat();
        } catch (IOException ex) {
            Logger.getLogger(SummaryStatistics.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEarningActionPerformed

    private void btnDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDurationActionPerformed
        try {
            // TODO add your handling code here:
            currentSelection = 3;
            btnRentalCount.setBackground(new Color(67,136,204));
            btnEarning.setBackground(new Color(67,136,204));
            btnDuration.setBackground(Color.blue);
            generateRentalDurationStat();
        } catch (IOException ex) {
            Logger.getLogger(SummaryStatistics.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDurationActionPerformed

    private void btnPrintChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintChartActionPerformed
        try {
            // TODO add your handling code here:
            printRecord(resultPanel);
        } catch (PrinterException ex) {
            Logger.getLogger(SummaryStatistics.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrintChartActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        AdminReportsDashboard dashboardPage = new AdminReportsDashboard(admin);
        dashboardPage.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPrint1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrint1ActionPerformed
        // TODO add your handling code here:
        carReport.setMonth((String) cboMonth.getSelectedItem());
        try {
            carReport.updateBookingList();
            switch(currentSelection){
                case 1:
                    generateRentalRateStat();
                    break;
                case 2:
                    generateRentalEarningStat();
                    break;
                default:
                    generateRentalDurationStat();
                    break;
                
            }
            
        } catch (IOException ex) {
            Logger.getLogger(SummaryStatistics.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnPrint1ActionPerformed

   private void printRecord(JPanel panel) throws PrinterException{
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        printerJob.setJobName("Print Record");
        printerJob.setPrintable(new Printable(){
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex){
                if(pageIndex>0){
                    return Printable.NO_SUCH_PAGE;
                }
                Graphics2D graphics2D = (Graphics2D) graphics;
                graphics2D.translate(pageFormat.getImageableX()*2, pageFormat.getImageableY()*2);
                graphics2D.scale(0.5, 0.5);
                panel.paint(graphics2D);
                
                return Printable.PAGE_EXISTS;
               
            }
          
        });
        
        boolean returningResult = printerJob.printDialog();
        if(returningResult){

            printerJob.print();
  
        }
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SummaryStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SummaryStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SummaryStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SummaryStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SummaryStatistics().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(SummaryStatistics.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDuration;
    private javax.swing.JButton btnEarning;
    private javax.swing.JButton btnPrint1;
    private javax.swing.JButton btnPrintChart;
    private javax.swing.JButton btnRentalCount;
    private javax.swing.JComboBox<String> cboMonth;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel resultPanel;
    // End of variables declaration//GEN-END:variables
}
